### ISSUE TITLE
LOve this but Ubuntu 16.04 not working

### ISSUE THREAD

**Issue by Iamwithin** [bulletmark/gmail-indicator#10]
I used this in Ubuntu 15.10 and installed it in Ubuntu 16.04 but now get this error:

~/bin/gmail-indicator -di
/home/bill/bin/gmail-indicator:14: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject
/home/bill/bin/gmail-indicator:15: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
2016-04-22 15:43.26 User = ****@gmail.com
2016-04-22 15:43.26 Server = imap.gmail.com, folder = "INBOX"
2016-04-22 15:43.26 Rates = fail:30, unread:60, read:300, reconnect:3600
2016-04-22 15:43.26 Command = /usr/bin/aplay /usr/share/sounds/purple/receive.wav
Traceback (most recent call last):
  File "/home/bill/bin/gmail-indicator", line 420, in <module>
    indicator = Indicator.create(folder)
  File "/home/bill/bin/gmail-indicator", line 217, in create
    return Indicator.UbuntuApp(label) if 'ubuntu' in desktop else \
  File "/home/bill/bin/gmail-indicator", line 185, in **init**
    from gi.repository import MessagingMenu
ImportError: cannot import name MessagingMenu

Any idea what I can do from here?

Thanks,

Bill

**Comment by bulletmark** [comment]
I actually don't use this app anymore but the warnings you report above were easy to fix with commit b61b6ccabc90b9843e9f77c4ccf6443845360a22.

The import error is something to do with the new Ubuntu 16.04. I have not used Ubuntu for years now so am not in a position to fix sorry.

**Comment by Iamwithin** [comment]
Thanks for the reply mate!

Bill

**Comment by Iamwithin** [comment]
Interestingly, I got this to work in Ubuntu 16.04 LTS by updating my
Ubuntu 15.10 release, and now I am really glad you created this!
However, no matter how I tried a clean install of 16.04 would not
let me install Gmail indicator.

Thanks again for this nice little program,
have a great life!

Bill in North Carolina, USA
